apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: testdb
spec:
  schemahero:
    image: "localhost:32000/schemahero/schemahero"
  immediateDeploy: true
  connection:
    mysql:
      # defaultCharset: utf16
      uri:
        value: testuser:password@tcp(10.43.153.43:3306)/testdb?tls=false
