apiVersion: databases.schemahero.io/v1alpha2
kind: Database
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: testdb
schemahero:
  image: "localhost:32000/schemahero/schemahero"
connection:
  postgres:
    uri:
      valueFrom:
        secretKeyRef:
          name: postgresql-secret
          key: uri
