apiVersion: databases.schemahero.io/v1alpha1
kind: Database
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: testdb
schemahero:
  image: "localhost:32000/schemahero/schemahero"
connection:
  postgres:
    uri:
      value: postgres://testuser:password@postgresql:5432/testdb?sslmode=disable
