apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: tables.schemas.schemahero.io
spec:
  group: schemas.schemahero.io
  names:
    kind: Table
    plural: tables
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            database:
              type: string
            name:
              type: string
            requires:
              items:
                type: string
              type: array
            schema:
              properties:
                postgres:
                  properties:
                    columns:
                      items:
                        properties:
                          constraints:
                            properties:
                              maxLength:
                                format: int64
                                type: integer
                              notNull:
                                type: boolean
                            required:
                            - maxLength
                            type: object
                          default:
                            type: string
                          name:
                            type: string
                          type:
                            type: string
                        required:
                        - name
                        - type
                        type: object
                      type: array
                    primaryKey:
                      items:
                        type: string
                      type: array
                  required:
                  - primaryKey
                  - columns
                  type: object
              required:
              - postgres
              type: object
          required:
          - database
          - name
          - requires
          - schema
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
