apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  uri: cG9zdGdyZXM6Ly9zY2hlbWFoZXJvOnBhc3N3b3JkQHBvc3RncmVzcWw6NTQzMi9naXRodWI=
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        chart: postgresql-3.18.1
      name: postgresql
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /bitnami/postgresql
        - name: POSTGRES_USER
          value: schemahero
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: github
        image: docker.io/bitnami/postgresql:10.7.0
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "schemahero" -d "github" -h 127.0.0.1
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: postgresql
        ports:
        - containerPort: 5432
          name: postgresql
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "schemahero" -d "github" -h 127.0.0.1
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: schemahero-github
          subPath: null
      initContainers:
      - command:
        - sh
        - -c
        - |
          chown -R 1001:1001 /bitnami
          if [ -d /bitnami/postgresql/data ]; then
            chmod  0700 /bitnami/postgresql/data;
          fi
        image: docker.io/bitnami/minideb:latest
        imagePullPolicy: Always
        name: init-chmod-data
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: schemahero-github
          subPath: null
      securityContext:
        fsGroup: 1001
      volumes: []
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: schemahero-github
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
