name: "Build and test"
on:
  push:
    tags-ignore: ["*"] # tags run tagged-release workflow
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14.1"
      - name: setup goenv
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - uses: actions/checkout@master
      - run: make all
      - uses: actions/upload-artifact@v1
        with:
          name: schemahero
          path: bin/schemahero
      - uses: actions/upload-artifact@v1
        with:
          name: manager
          path: bin/manager
      - uses: actions/upload-artifact@v1
        with:
          name: kubectl-schemahero
          path: bin/kubectl-schemahero

  ## We list each here so that they all show up in the output of github checks
  test-postgres:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/postgres/column-set-default run
      - run: make -C integration/tests/postgres/column-unset-default run
      - run: make -C integration/tests/postgres/create-table run
      - run: make -C integration/tests/postgres/foreign-key-create run
      - run: make -C integration/tests/postgres/foreign-key-action run
      - run: make -C integration/tests/postgres/foreign-key-drop run
      - run: make -C integration/tests/postgres/foreign-key-alter run
      - run: make -C integration/tests/postgres/not-null run
      - run: make -C integration/tests/postgres/index-create run
      - run: make -C integration/tests/postgres/primary-key-add run
      - run: make -C integration/tests/postgres/primary-key-drop run

  ## We list each here so that they all show up in the output of github checks
  test-mysql:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/mysql/column-set-default run
      - run: make -C integration/tests/mysql/column-unset-default run
      - run: make -C integration/tests/mysql/create-table run
      - run: make -C integration/tests/mysql/foreign-key-create run
      - run: make -C integration/tests/mysql/foreign-key-action run
      - run: make -C integration/tests/mysql/foreign-key-drop run
      - run: make -C integration/tests/mysql/foreign-key-alter run
      - run: make -C integration/tests/mysql/not-null run
      - run: make -C integration/tests/mysql/index-create run
      - run: make -C integration/tests/mysql/primary-key-add run
      - run: make -C integration/tests/mysql/primary-key-drop run

  ## We list each here so that they all show up in the output of github checks
  test-cockroach:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: action/checkout@master
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/cockroach run TEST_NAME=column-set-default
      - run: make -C integration/tests/cockroach run TEST_NAME=column-unset-default
      - run: make -C integration/tests/cockroach run TEST_NAME=create-table
      - run: make -C integration/tests/cockroach run TEST_NAME=foreign-key-create
      - run: make -C integration/tests/cockroach run TEST_NAME=foreign-key-action
      - run: make -C integration/tests/cockroach run TEST_NAME=foreign-key-drop
      - run: make -C integration/tests/cockroach run TEST_NAME=foreign-key-alter
      - run: make -C integration/tests/cockroach run TEST_NAME=not-null
      - run: make -C integration/tests/cockroach run TEST_NAME=index-create
      - run: make -C integration/tests/cockroach run TEST_NAME=primary-key-add
      - run: make -C integration/tests/cockroach run TEST_NAME=primary-key-drop

  kots:
    runs-on: ubuntu-latest
    name: kots
    needs: [test-mysql, test-postgres]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download kubectl-schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: kubectl-schemahero
          path: bin/
      - run: chmod +x bin/kubectl-schemahero

      - uses: azure/docker-login@v1
        with:
          login-server: registry.replicated.com
          username: ${{ secrets.REPLICATED_API_TOKEN }}
          password: ${{ secrets.REPLICATED_API_TOKEN }}
      - run: make kotsimages

      - run: ./bin/kubectl-schemahero install --yaml --out-dir=./kots --enterprise --namespace="repl{{ Namespace }}" --enterprise-tag=alpha

      - name: Lint the release
        id: lint-action
        uses: replicatedhq/action-kots-lint@v0.1.0
        with:
          replicated-app: "schemahero-enterprise"
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: kots

      - name: Create the release
        id: test-action
        uses: replicatedhq/action-kots-release@v0.2.0
        with:
          replicated-app: "schemahero-enterprise"
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: kots
