name: "Tagged release"
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1.1.2
        with:
          go-version: "1.14.1"
      - name: setup goenv
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - uses: actions/checkout@v2
      - run: make all
      - uses: actions/upload-artifact@v1
        with:
          name: schemahero
          path: bin/schemahero
      - uses: actions/upload-artifact@v1
        with:
          name: manager
          path: bin/manager
      - uses: actions/upload-artifact@v1
        with:
          name: kubectl-schemahero
          path: bin/kubectl-schemahero

  test-postgres:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/postgres run

  test-mysql:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/mysql run

  test-cockroach:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/cockroach run

  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - test-postgres
      - test-mysql
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v1.1.2
        with:
          go-version: "1.14.1"
      - uses: azure/docker-login@v1
        with:
          username: schemaherodeploy
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.5.1
        with:
          version: latest
          args: release --rm-dist --config deploy/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
