name: "Tagged release"
on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.12.14"
      - name: setup goenv
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - uses: actions/checkout@master
      - name: setup kubebuilder
        run: |
          echo "::add-path::/usr/local/kubebuilder/bin"
      - run: make kubebuilder all
      - uses: actions/upload-artifact@v1
        with:
          name: schemahero
          path: bin/schemahero
      - uses: actions/upload-artifact@v1
        with:
          name: manager
          path: bin/manager
      - uses: actions/upload-artifact@v1
        with:
          name: kubectl-schemahero
          path: bin/kubectl-schemahero

  ## We list each here so that they all show up in the output of github checks
  test-postgres:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/postgres/column-set-default run
      - run: make -C integration/tests/postgres/column-unset-default run
      - run: make -C integration/tests/postgres/create-table run
      - run: make -C integration/tests/postgres/foreign-key-create run
      - run: make -C integration/tests/postgres/foreign-key-action run
      - run: make -C integration/tests/postgres/foreign-key-drop run
      - run: make -C integration/tests/postgres/foreign-key-alter run
      - run: make -C integration/tests/postgres/not-null run
      - run: make -C integration/tests/postgres/index-create run
      - run: make -C integration/tests/postgres/primary-key-add run
      - run: make -C integration/tests/postgres/primary-key-drop run

  ## We list each here so that they all show up in the output of github checks
  test-mysql:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Download schemahero binary
        uses: actions/download-artifact@v1
        with:
          name: schemahero
          path: bin/
      - run: chmod +x bin/schemahero
      - run: make -C integration/tests/mysql/column-set-default run
      - run: make -C integration/tests/mysql/column-unset-default run
      - run: make -C integration/tests/mysql/create-table run
      - run: make -C integration/tests/mysql/foreign-key-create run
      - run: make -C integration/tests/mysql/foreign-key-action run
      - run: make -C integration/tests/mysql/foreign-key-drop run
      - run: make -C integration/tests/mysql/foreign-key-alter run
      - run: make -C integration/tests/mysql/not-null run
      - run: make -C integration/tests/mysql/index-create run
      - run: make -C integration/tests/mysql/primary-key-add run
      - run: make -C integration/tests/mysql/primary-key-drop run

  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - test-postgres
      - test-mysql
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v1
        with:
          go-version: "1.12.14"
      - uses: azure/docker-login@v1
        with:
          username: schemaherodeploy
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config deploy/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
